# Generated by Django 2.1.13 on 2019-10-14 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentmethod',
            name='service_fee',
            field=models.FloatField(max_length=4),
        ),
        migrations.AlterField(
            model_name='pricing',
            name='price_per_km',
            field=models.FloatField(max_length=5),
        ),
    ]
