# Generated by Django 2.1.13 on 2019-12-12 06:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Payment', '0003_auto_20191128_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='pricing',
            name='fixed_fare',
            field=models.FloatField(default=0.0, max_length=5),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='pricing',
            name='user_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
