# Generated by Django 2.1.13 on 2019-10-08 16:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Verify', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email_otp',
            new_name='otp',
        ),
    ]
