# Generated by Django 2.1.13 on 2019-10-08 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Verify', '0002_auto_20191008_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_email_verified',
            new_name='is_verified',
        ),
        migrations.RemoveField(
            model_name='user',
            name='is_phone_verified',
        ),
    ]
