# Generated by Django 2.1.13 on 2019-10-09 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Verify', '0004_auto_20191009_2332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
