# Generated by Django 2.1.13 on 2019-10-09 18:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Verify', '0005_auto_20191009_2334'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='payment_method_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='reservation_id',
        ),
        migrations.RemoveField(
            model_name='payment',
            name='user_id',
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
