# Generated by Django 2.1.13 on 2019-10-09 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Verify', '0006_auto_20191009_2341'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='UserRideDetails',
            new_name='UserRideDetail',
        ),
    ]
