# Generated by Django 2.1.13 on 2019-10-09 18:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Verify', '0007_auto_20191009_2344'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userridedetail',
            name='payment_method_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Verify.PaymentMethod'),
        ),
        migrations.AlterField(
            model_name='userridedetail',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
