# Generated by Django 2.2.9 on 2020-02-24 19:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Payment', '0001_initial'),
        ('Reservation', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserRideDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kilometer', models.FloatField(blank=True, null=True)),
                ('price_per_km', models.FloatField(blank=True, max_length=5, null=True)),
                ('payment_status', models.BooleanField(default=False)),
                ('fare', models.IntegerField()),
                ('fixed_fare', models.BooleanField(default=False)),
                ('pick_up_point', models.CharField(blank=True, max_length=256)),
                ('pick_up_time', models.TimeField(blank=True, null=True)),
                ('drop_off_point', models.CharField(blank=True, max_length=256)),
                ('drop_off_time', models.TimeField(blank=True, null=True)),
                ('ride_status', models.CharField(default='ACTIVE', max_length=20)),
                ('ride_date', models.DateTimeField(blank=True, null=True)),
                ('admin_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('payment_method_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Payment.PaymentMethod')),
                ('reservation_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservation.Reservation')),
                ('ride_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservation.Ride')),
            ],
        ),
    ]
