# Generated by Django 2.1.13 on 2019-10-14 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideSchedule', '0002_userridedetail_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userridedetail',
            name='kilometer',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='userridedetail',
            name='price_per_km',
            field=models.FloatField(max_length=5),
        ),
    ]
