# Generated by Django 2.1.13 on 2019-10-15 05:40

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideSchedule', '0003_auto_20191014_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userridedetail',
            name='ride_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
