# Generated by Django 2.1.13 on 2019-11-28 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideSchedule', '0004_auto_20191015_1040'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userridedetail',
            old_name='total_payment',
            new_name='fare',
        ),
        migrations.AlterField(
            model_name='userridedetail',
            name='kilometer',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userridedetail',
            name='price_per_km',
            field=models.FloatField(blank=True, max_length=5, null=True),
        ),
    ]
