# Generated by Django 2.1.13 on 2019-11-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideSchedule', '0005_auto_20191128_0954'),
    ]

    operations = [
        migrations.AddField(
            model_name='userridedetail',
            name='fixed_fare',
            field=models.BooleanField(default=False),
        ),
    ]
