# Generated by Django 2.1.13 on 2019-12-06 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RideSchedule', '0006_userridedetail_fixed_fare'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userridedetail',
            old_name='user_id',
            new_name='admin_id',
        ),
    ]
