# Generated by Django 2.1.13 on 2019-12-12 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RideSchedule', '0007_auto_20191206_1611'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userridedetail',
            old_name='drop_up_point',
            new_name='drop_off_point',
        ),
    ]
