# Generated by Django 2.1.13 on 2019-12-23 05:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideSchedule', '0008_auto_20191212_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='userridedetail',
            name='ride_status',
            field=models.CharField(choices=[('complete', 'COMPLETE'), ('incomplete', 'INCOMPLETE'), ('cancelled', 'CANCELLED')], default='green', max_length=6),
        ),
    ]
