# Generated by Django 2.2.9 on 2020-01-23 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideSchedule', '0010_auto_20200123_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='userridedetail',
            name='ride_arrival_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
