# Generated by Django 2.2.9 on 2020-02-14 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideSchedule', '0011_userridedetail_ride_arrival_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userridedetail',
            name='ride_status',
            field=models.CharField(choices=[('complete', 'COMPLETED'), ('incomplete', 'INCOMPLETE'), ('cancelled', 'CANCELLED'), ('pending', 'PENDING'), ('active', 'ACTIVE')], default='pending', max_length=10),
        ),
    ]
