# Generated by Django 2.2.9 on 2020-02-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideSchedule', '0012_auto_20200214_1805'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userridedetail',
            name='ride_status',
            field=models.CharField(default='ACTIVE', max_length=10),
        ),
    ]
