# Generated by Django 2.2.9 on 2020-02-20 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RideSchedule', '0013_auto_20200214_1810'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userridedetail',
            old_name='ride_arrival_time',
            new_name='drop_off_time',
        ),
        migrations.AddField(
            model_name='userridedetail',
            name='pick_up_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='userridedetail',
            name='ride_status',
            field=models.CharField(default='ACTIVE', max_length=20),
        ),
    ]
