# Generated by Django 2.1.13 on 2019-10-17 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20191017_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp_time',
            field=models.DateTimeField(),
        ),
    ]
