# Generated by Django 2.1.13 on 2019-10-18 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0003_auto_20191017_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='otp_counter',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userotp',
            name='otp',
            field=models.CharField(default=None, max_length=8, null=True),
        ),
    ]
