# Generated by Django 2.1.13 on 2019-10-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0004_auto_20191018_1115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotp',
            name='otp_counter',
            field=models.IntegerField(default=0),
        ),
    ]
