# Generated by Django 2.1.13 on 2019-10-30 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0005_auto_20191020_2316'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotp',
            name='password_reset_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
