# Generated by Django 2.1.13 on 2019-11-18 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0006_userotp_password_reset_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('support', models.EmailField(default='supprot@example.com', max_length=254)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
