# Generated by Django 2.1.13 on 2019-11-28 04:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0007_sitesettings'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteSettings',
        ),
    ]
