# Generated by Django 2.1.13 on 2019-12-12 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0009_auto_20191210_1243'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default=None, max_length=15, unique=True),
        ),
    ]
