# Generated by Django 2.2.9 on 2020-02-24 20:14

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField(blank=True, null=True)),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('seats_left', models.IntegerField()),
                ('is_complete', models.BooleanField(default=False)),
                ('driver_ids', models.ManyToManyField(to='User.Captain')),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('latitude', models.FloatField(max_length=100)),
                ('longitude', models.FloatField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_no_plate', models.CharField(max_length=10)),
                ('brand', models.CharField(blank=True, max_length=20)),
                ('max_seats', models.IntegerField()),
                ('from_loc', models.CharField(blank=True, max_length=255)),
                ('to_loc', models.CharField(blank=True, max_length=255)),
                ('driver_ids', models.ManyToManyField(blank=True, related_name='drivers', to='User.Captain')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Captain')),
            ],
        ),
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('route_id', models.CharField(blank=True, max_length=10, null=True)),
                ('start_name', models.CharField(max_length=50)),
                ('stop_name', models.CharField(max_length=50)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('ride_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ride_route', to='Reservation.Ride')),
                ('stop_ids', models.ManyToManyField(related_name='route_stops', to='Reservation.Stop')),
            ],
        ),
        migrations.AddField(
            model_name='ride',
            name='vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_vehicle', to='Reservation.Vehicle'),
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reservation_number', models.CharField(max_length=20, unique=True)),
                ('reservation_seats', models.IntegerField()),
                ('is_confirmed', models.BooleanField(default=False)),
                ('created_date', models.DateField(default=datetime.datetime.today)),
                ('updated_timestamp', models.DateTimeField(blank=True, null=True)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Customer')),
                ('ride_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservation.Ride')),
            ],
        ),
    ]
