# Generated by Django 2.1.13 on 2019-10-11 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Reservation', '0001_initial'),
        ('User', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='driver_ids',
            field=models.ManyToManyField(blank=True, related_name='drivers', to='User.Captain'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Captain'),
        ),
        migrations.AddField(
            model_name='ride',
            name='driver_ids',
            field=models.ManyToManyField(to='User.Captain'),
        ),
        migrations.AddField(
            model_name='ride',
            name='vehicle_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_vehicle', to='Reservation.Vehicle'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='customer_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='User.Customer'),
        ),
        migrations.AddField(
            model_name='reservation',
            name='ride_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Reservation.Ride'),
        ),
    ]
