# Generated by Django 2.1.13 on 2019-10-15 05:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0002_auto_20191011_1717'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='created_date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
