# Generated by Django 2.1.13 on 2019-11-29 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0005_auto_20191017_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='from_loc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='to_loc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_no_plate',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
