# Generated by Django 2.1.13 on 2019-12-01 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0006_auto_20191129_1040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='route',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
