# Generated by Django 2.1.13 on 2019-12-01 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0007_auto_20191201_2233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_lat_long', models.CharField(max_length=100)),
                ('start_name', models.CharField(max_length=50)),
                ('stop_lat_long', models.CharField(max_length=100)),
                ('stop_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lat_long', models.CharField(max_length=100)),
                ('route_id', models.ManyToManyField(related_name='route_stops', to='Reservation.Route')),
            ],
        ),
        migrations.RemoveField(
            model_name='ride',
            name='route',
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='from_loc',
            field=models.CharField(default='K', max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='to_loc',
            field=models.CharField(default='L', max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_no_plate',
            field=models.CharField(max_length=10),
        ),
        migrations.AddField(
            model_name='ride',
            name='route_id',
            field=models.ManyToManyField(related_name='ride_route', to='Reservation.Route'),
        ),
    ]
