# Generated by Django 2.1.13 on 2019-12-02 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0008_auto_20191201_2246'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='route_id',
        ),
        migrations.RemoveField(
            model_name='route',
            name='start_lat_long',
        ),
        migrations.RemoveField(
            model_name='route',
            name='stop_lat_long',
        ),
        migrations.AlterField(
            model_name='stop',
            name='name',
            field=models.CharField(max_length=256),
        ),
    ]
