# Generated by Django 2.1.13 on 2019-12-02 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0009_auto_20191202_1249'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='ride_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='ride_route', to='Reservation.Ride'),
            preserve_default=False,
        ),
    ]
