# Generated by Django 2.1.13 on 2019-12-02 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0010_route_ride_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stop',
            old_name='route_id',
            new_name='route_ids',
        ),
    ]
