# Generated by Django 2.1.13 on 2019-12-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0011_auto_20191202_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='is_complete',
            field=models.BooleanField(default=False),
        ),
    ]
