# Generated by Django 2.1.13 on 2019-12-02 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0012_ride_is_complete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stop',
            old_name='lat_long',
            new_name='latitude',
        ),
        migrations.AddField(
            model_name='stop',
            name='longitude',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
