# Generated by Django 2.1.13 on 2019-12-10 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0015_auto_20191210_1243'),
    ]

    operations = [
        migrations.RenameField(
            model_name='route',
            old_name='route_ids',
            new_name='stop_ids',
        ),
    ]
