# Generated by Django 2.2.9 on 2020-02-11 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0016_auto_20191210_1245'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='from_loc',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='to_loc',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
