# Generated by Django 2.2.9 on 2020-02-21 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Reservation', '0017_auto_20200211_1044'),
    ]

    operations = [
        migrations.AddField(
            model_name='route',
            name='route_id',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
